[project]
name = "cq-gridbase"
dependencies = [
  "cadquery",
  "cqwild",
]
dynamic = ["version", "readme"]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.setuptools.dynamic]
readme = {file = ["README.md"]}
